// ==============================================================================
// File: src/services/enquiryService.ts
// Description: Public Enquiry Service Layer for Job Seekers & Corporate Employers
// Brand: A TIGER GROUPS — Certified Recruitment & Manpower Solutions
// Features: Server-side validation, authoritative PostgreSQL-generated identifiers,
//           in-flight duplicate submission locking, and real Supabase persistence.
// ==============================================================================

import { supabase } from '../lib/supabaseClient';

export interface CreateJobSeekerInput {
  fullName: string;
  fatherName: string;
  mobile: string;
  email: string;
  address: string;
  desiredCompany: string;
  designation: string;
  description?: string;
}

export interface CreateJobSeekerResult {
  success: boolean;
  applicationId?: string;
  applicationNumber?: string;
  error?: string;
}

export interface CreateEmployerEnquiryInput {
  companyName: string;
  email: string;
  phone: string;
  address: string;
  district: string;
  state: string;
  employeesRequired: number;
  jobRole: string;
  description?: string;
}

export interface CreateEmployerEnquiryResult {
  success: boolean;
  enquiryId?: string;
  enquiryNumber?: string;
  error?: string;
}

// In-flight submission locks to prevent duplicate submissions from rapid multi-clicks
const activeJobSeekerSubmissions = new Set<string>();
const activeEmployerSubmissions = new Set<string>();

const EMAIL_REGEX = /^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$/;
const INDIAN_PHONE_REGEX = /^[6-9]\d{9}$/;

/**
 * Validates and submits a new Candidate Job Seeker Application to Supabase.
 * - Enforces required fields including email
 * - Enforces server-side validation
 * - Application number is strictly database-generated by PostgreSQL (INQ-YYYY-000001)
 * - Browser cannot choose or forge an application number
 * - Returns database application ID and application number
 */
export async function createJobSeekerApplication(
  input: CreateJobSeekerInput
): Promise<CreateJobSeekerResult> {
  const trimmedName = input.fullName?.trim() || '';
  const trimmedFatherName = input.fatherName?.trim() || '';
  const rawMobile = input.mobile?.trim() || '';
  const normalizedMobile = rawMobile.replace(/^(?:\+91|91|0)/, '').replace(/\D/g, '');
  const trimmedEmail = input.email?.trim().toLowerCase() || '';
  const trimmedAddress = input.address?.trim() || '';
  const trimmedCompany = input.desiredCompany?.trim() || '';
  const trimmedDesignation = input.designation?.trim() || '';
  const trimmedDescription = input.description?.trim() || null;

  // 1. Server-Side Validation
  if (!trimmedName || trimmedName.length < 2) {
    return { success: false, error: 'Full Name is required (minimum 2 characters).' };
  }
  if (!trimmedFatherName || trimmedFatherName.length < 2) {
    return { success: false, error: "Father's Name is required (minimum 2 characters)." };
  }
  if (!normalizedMobile || !INDIAN_PHONE_REGEX.test(normalizedMobile)) {
    return {
      success: false,
      error: 'A valid 10-digit Indian mobile number is required (starting with 6, 7, 8, or 9).'
    };
  }
  if (!trimmedEmail || !EMAIL_REGEX.test(trimmedEmail)) {
    return {
      success: false,
      error: 'A valid email address is required for candidate registration and future notifications.'
    };
  }
  if (!trimmedAddress || trimmedAddress.length < 5) {
    return { success: false, error: 'Full residential address is required.' };
  }
  if (!trimmedCompany) {
    return { success: false, error: 'Please select a preferred company / organization.' };
  }
  if (!trimmedDesignation || trimmedDesignation.length < 2) {
    return { success: false, error: 'Designation / job position is required.' };
  }

  // 2. Concurrency / In-Flight Duplicate Locking
  const lockKey = `${trimmedEmail}:${normalizedMobile}`;
  if (activeJobSeekerSubmissions.has(lockKey)) {
    return {
      success: false,
      error: 'An application submission is already in progress. Please wait.'
    };
  }
  activeJobSeekerSubmissions.add(lockKey);

  try {
    // 3. Database Insertion — Do NOT pass application_number; PostgreSQL triggers assign INQ-YYYY-000001
    const { data, error } = await supabase
      .from('applications')
      .insert({
        full_name: trimmedName,
        father_name: trimmedFatherName,
        mobile: normalizedMobile,
        email: trimmedEmail,
        address: trimmedAddress,
        desired_company: trimmedCompany,
        designation: trimmedDesignation,
        description: trimmedDescription,
        status: 'NEW_ENQUIRY',
        joining_access_enabled: false
      })
      .select('id, application_number')
      .single();

    if (error) {
      console.error('[createJobSeekerApplication] Supabase database error:', error.message);
      return {
        success: false,
        error: error.message || 'Failed to submit candidate application to database.'
      };
    }

    if (!data || !data.id || !data.application_number) {
      return {
        success: false,
        error: 'Application was processed but failed to return confirmation details from server.'
      };
    }

    return {
      success: true,
      applicationId: data.id,
      applicationNumber: data.application_number
    };
  } catch (err: unknown) {
    console.error('[createJobSeekerApplication] Unexpected exception during submission:', err);
    return {
      success: false,
      error: err instanceof Error ? err.message : 'A network or server error occurred during submission.'
    };
  } finally {
    activeJobSeekerSubmissions.delete(lockKey);
  }
}

/**
 * Validates and submits an Employer Corporate Manpower Requirement to Supabase.
 * - Enforces required fields
 * - Reference number is strictly database-generated by PostgreSQL (EMP-YYYY-000001)
 * - Returns database enquiry ID and reference number
 */
export async function createEmployerEnquiry(
  input: CreateEmployerEnquiryInput
): Promise<CreateEmployerEnquiryResult> {
  const trimmedCompany = input.companyName?.trim() || '';
  const trimmedEmail = input.email?.trim().toLowerCase() || '';
  const rawPhone = input.phone?.trim() || '';
  const normalizedPhone = rawPhone.replace(/^(?:\+91|91|0)/, '').replace(/\D/g, '');
  const trimmedAddress = input.address?.trim() || '';
  const trimmedDistrict = input.district?.trim() || '';
  const trimmedState = input.state?.trim() || '';
  const employeesRequired = Number(input.employeesRequired);
  const trimmedRole = input.jobRole?.trim() || '';
  const trimmedDescription = input.description?.trim() || null;

  // 1. Server-Side Validation
  if (!trimmedCompany || trimmedCompany.length < 2) {
    return { success: false, error: 'Company / Firm name is required.' };
  }
  if (!trimmedEmail || !EMAIL_REGEX.test(trimmedEmail)) {
    return { success: false, error: 'A valid official corporate email is required.' };
  }
  if (!normalizedPhone || !INDIAN_PHONE_REGEX.test(normalizedPhone)) {
    return { success: false, error: 'A valid 10-digit contact phone number is required.' };
  }
  if (!trimmedAddress || trimmedAddress.length < 5) {
    return { success: false, error: 'Plant / Office address is required.' };
  }
  if (!trimmedDistrict) {
    return { success: false, error: 'District / City is required.' };
  }
  if (!trimmedState) {
    return { success: false, error: 'State selection is required.' };
  }
  if (isNaN(employeesRequired) || employeesRequired <= 0) {
    return { success: false, error: 'Number of employees required must be at least 1.' };
  }
  if (!trimmedRole || trimmedRole.length < 2) {
    return { success: false, error: 'Job role / nature of work is required.' };
  }

  // 2. Concurrency / In-Flight Duplicate Locking
  const lockKey = `${trimmedEmail}:${trimmedCompany}`;
  if (activeEmployerSubmissions.has(lockKey)) {
    return {
      success: false,
      error: 'An employer requirement submission is already in progress. Please wait.'
    };
  }
  activeEmployerSubmissions.add(lockKey);

  try {
    // 3. Database Insertion — Do NOT pass enquiry_number; PostgreSQL triggers assign EMP-YYYY-000001
    const { data, error } = await supabase
      .from('employer_enquiries')
      .insert({
        company_name: trimmedCompany,
        email: trimmedEmail,
        phone: normalizedPhone,
        address: trimmedAddress,
        district: trimmedDistrict,
        state: trimmedState,
        employees_required: employeesRequired,
        job_role: trimmedRole,
        description: trimmedDescription,
        status: 'NEW'
      })
      .select('id, enquiry_number')
      .single();

    if (error) {
      console.error('[createEmployerEnquiry] Supabase database error:', error.message);
      return {
        success: false,
        error: error.message || 'Failed to submit employer requirement to database.'
      };
    }

    if (!data || !data.id) {
      return {
        success: false,
        error: 'Employer enquiry was submitted but failed to return confirmation ID.'
      };
    }

    return {
      success: true,
      enquiryId: data.id,
      enquiryNumber: data.enquiry_number || undefined
    };
  } catch (err: unknown) {
    console.error('[createEmployerEnquiry] Unexpected exception during submission:', err);
    return {
      success: false,
      error: err instanceof Error ? err.message : 'A network or server error occurred during submission.'
    };
  } finally {
    activeEmployerSubmissions.delete(lockKey);
  }
}
